# Generated by Django 5.0.3 on 2024-03-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('board', models.CharField(choices=[('Cambridge', 'Cambridge'), ('Edexcel', 'Edexcel')], max_length=100)),
                ('paper_code', models.CharField(max_length=15)),
                ('qualifications', models.CharField(choices=[('A Level', 'A Level'), ('O Level', 'O Level')], max_length=50)),
                ('exam_type', models.CharField(choices=[('Written Exam', 'Written Exam'), ('Practial Exam', 'Practial Exam')], max_length=50)),
                ('syllabus', models.CharField(max_length=100)),
                ('exam_duration', models.DurationField()),
                ('time_slot', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=5)),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('unique_candidate', models.CharField(max_length=20)),
                ('candidate_number', models.CharField(max_length=20)),
                ('center_number', models.CharField(max_length=20)),
                ('school_number', models.CharField(max_length=20)),
                ('center_type', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('DHAKA', 'DHAKA'), ('CHITTAGONG', 'CHITTAGONG'), ('RAJSHAHI', 'RAJSHAHI')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
