# Generated by Django 5.0.3 on 2024-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='board',
            new_name='Board',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='candidate_number',
            new_name='Candidate_number',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='center_number',
            new_name='Center_number',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='center_type',
            new_name='Center_type',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_duration',
            new_name='Duration',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='end_time',
            new_name='End_time',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_type',
            new_name='Exam_type',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='paper_code',
            new_name='Paper_code',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='qualifications',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='session',
            new_name='Session',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='start_time',
            new_name='Start_time',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='syllabus',
            new_name='Syllabus',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='time_slot',
            new_name='Time_slot',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='zone',
            new_name='Zone',
        ),
        migrations.AlterField(
            model_name='exam',
            name='school_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='unique_candidate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
