# Generated by Django 5.0.3 on 2024-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_board_exam_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Location',
            field=models.CharField(choices=[('DHAKA', 'DHAKA'), ('CHITTAGONG', 'CHITTAGONG'), ('RAJSHAHI', 'RAJSHAHI'), ('SYLHET', 'SYLHET')], max_length=30),
        ),
    ]
