# Generated by Django 5.0.3 on 2024-03-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='End_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Start_time',
            field=models.DateTimeField(),
        ),
    ]
